### ISSUE TITLE
"Stream" option not sending captions to YouTube

### ISSUE THREAD

**Issue by RodriMora** [locaal-ai/obs-localvocal#110]
Hi!

I have the "Stream" option checked, and in the youtube live studio I have enabled the "Closed Captions" as "Embedded 608/708" but they don't show up when toggling the "CC" option in the youtube live player. 
Is there anything else I need to setup for this to work? I don't even know if this is the correct procedure.

Thanks!

**Comment by royshil** [comment]
@RodriMora this should work, the code is supposed to be sending it
but only if you have a stream through OBS to youtube open and streaming

there is an option in the filter that must be enabled
![image](https://github.com/occ-ai/obs-localvocal/assets/441170/f6856597-e2d9-49c0-95fe-e5dd2f906c47)

**Comment by RodriMora** [comment]
> @RodriMora this should work, the code is supposed to be sending it but only if you have a stream through OBS to youtube open and streaming
> 
> there is an option in the filter that must be enabled ![image](https://private-user-images.githubusercontent.com/441170/338736996-f6856597-e2d9-49c0-95fe-e5dd2f906c47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMzg1MTYsIm5iZiI6MTcxODEzODIxNiwicGF0aCI6Ii80NDExNzAvMzM4NzM2OTk2LWY2ODU2NTk3LWUyZDktNDljMC05NWZlLWU1ZGQyZjkwNmM0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQyMDM2NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Njc0MzI2YTNmNDBjODRjMjZkYjI5ZDMyNDRjNDQyYmIzYTgwYTcwNzQ1NTQwY2Q2YWJkZDU4YmZmNjYxOTM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eo62rSYOvBoaz2BNKhQZWgpYg4cWUGPMvP9WhOdiUOk)

does it work with stream key, or do I need to be logged in into youtube for it to work, or it doesn't matter?

**Comment by royshil** [comment]
You just need to be streaming through OBS and not an external program.
To stream through OBS you need to be logged in or otherwise set it up for YouTube live streaming

**Comment by royshil** [comment]
@RodriMora can you test the latest version please?

**Comment by RodriMora** [comment]
Hi!

I think it works now. I can see the subtitles using Embedded 608/708. 

But when I stop talking, the last sentence gets stuck on screen (I don't know if that's how it should work) until I start talking again, but then if 2 sentences come quickly the first one would not appear.
