### ISSUE TITLE
Twitch captions issues

### ISSUE THREAD

**Issue by Petarkco** [locaal-ai/obs-localvocal#114]
I've previously been a user of this plug in (https://github.com/ratwithacompiler/OBS-captions-plugin) and found it works well.

I tried localvocal today and had a couple of issues. My use case is transcribing audio from VHS tapes and sending it only to Twitch through the native captions system.

localvocal seemed to send captions in batches regardless of the settings I used. I turned on buffering (2/3 lines), and print special, progress and real time (this causes the captions to be delayed). These settings seem to work well locally but doesn't seem to work with twitch. I'd prefer the captions to appear in real time on Twitch.
![image](https://github.com/occ-ai/obs-localvocal/assets/25685344/d6b961dd-cce6-401f-83ca-0e2bdbaef819)
![image](https://github.com/occ-ai/obs-localvocal/assets/25685344/8668b8d9-55ee-40c4-b14d-bda271294757)

More than happy to help debug.

**Comment by royshil** [comment]
so the captions are being sent to twitch just don't appear in real-time?

**Comment by Petarkco** [comment]
That's correct.

**Comment by royshil** [comment]
@Petarkco can you test #145 ? i think i resolved it

**Comment by Petarkco** [comment]
> @Petarkco can you test #145 ? i think i resolved it

Once a new build is released. I can :P

**Comment by royshil** [comment]
@Petarkco shuold be resolved by v0.3.4

**Comment by royshil** [comment]
resolved

**Comment by Teravus** [comment]
I just wanted to say, this is the only thing that I've seen that indicates that the plugin supports sending native player closed captions.  Everything else in the documentation, at a glance, seemed to indicate that I'd need to make a gdi+ text box for them (but, I didn't want text on screen that the viewer can't, themselves, control the visibility).   As a result of seeing this, I will try the plugin.   Thank you!
