### ISSUE TITLE
0.3.1 and 0.3.2 crash OBS on Win10

### ISSUE THREAD

**Issue by 211ca690** [locaal-ai/obs-localvocal#127]
Happens upon adding LocalVocal filter to audio source.
Used CUDA12 and CPU installers from "Releases" page - same result.
0.3.0 is the last version that works.
[2024-07-06 22-14-36.txt](https://github.com/user-attachments/files/16116040/2024-07-06.22-14-36.txt)
[Crash 2024-07-06 22-14-45.txt](https://github.com/user-attachments/files/16116041/Crash.2024-07-06.22-14-45.txt)

**Comment by royshil** [comment]
can yo please test #126 
i'm fixing the crash bug

**Comment by royshil** [comment]
@211ca690 can you please check the latest version?

**Comment by royshil** [comment]
glad to see it fixed!
