### ISSUE TITLE
Can we add distil-whisper?

### ISSUE THREAD

**Issue by FerLuisxd** [locaal-ai/obs-localvocal#167]
[Distil-whisper](https://github.com/huggingface/distil-whisper) is apparently the fastest whisper implementation (from the guy that created whisper JAX), and runs on the CPU, it could be nice to see it here!

**Comment by royshil** [comment]
i do have a few distil options alreayd in there and you're also able to use any external model file if you have the GGUF version

**Comment by royshil** [comment]
resolved

**Comment by zenny** [comment]
> resolved

@royshil Glad to see this was resolved pretty fast.

Appreciate if you post some installation instructions that one can integrate distil-whisper with obs-localvocal and/or obs/squawk? Thanks.
