### ISSUE TITLE
Automatic file renaming only works when SRT format is checked

### ISSUE THREAD

**Issue by schrauger** [locaal-ai/obs-localvocal#173]
When outputting transcriptions to a file, the "Rename file to match recording" checkbox doesn't do anything unless the "Save in SRT format" is also checked.

I would like to save a text-only transcript without SRT timestamps and have it automatically renamed to match with the video recording name. I expected the Rename feature to work that way, but it doesn't seem to actually rename the file unless I also have SRT format checked.

It would be helpful to allow the Rename functionality to work even without SRT format output, and since the Rename functionality can be enabled independently from the SRT formatting option, I assume this is a bug.

**Comment by royshil** [comment]
fixed in #179

**Comment by royshil** [comment]
done
