### ISSUE TITLE
Only "Whisper-Based Translation" Translates

### ISSUE THREAD

**Issue by technohippies** [locaal-ai/obs-localvocal#176]
Firstly, thanks for such an awesome plugin.

I cannot get any translations to show, unless I use Whisper-Based Translation, in which case the original subtitles in English don't show either (as you described in your YT video).

- I'm using the newest version 0.3.7
- Whisper Tiny works great for English transcription 
- I've tried both the M2M-100 418 model, and the NLLB 200 600M model, with many different languages
- It's not a font related problem: 1. Spanish doens't work, and 2. If I manually paste something into the Text field, it shows
- I'm running a Linux Ubuntu distro with an Nvidia GPU

My main solution could be to run 2 instances of the Audio Filter, with another running Whisper-Based Translation, but I'm guessing this would further cook my GPU.

Not sure what I'm doing wrong. Any help appreciated!

![image](https://github.com/user-attachments/assets/a2a961bc-612b-489e-85c8-fc521320c315)

**Comment by royshil** [comment]
duplicate
