### ISSUE TITLE
Feature request : Readme file update for version info

### ISSUE THREAD

**Issue by iNgeon** [locaal-ai/obs-localvocal#178]
Please would you add some basic info in the Readme.md file on the different version, pro's and cons etc
See there is a windows-x64-cpu & windows-x64-cuda & windows-x64-hipblas
For new users interested, noobs etc

**Comment by royshil** [comment]
that's a great idea!

**Comment by iNgeon** [comment]
Completed, thank you
https://github.com/locaal-ai/obs-localvocal/blob/master/README.md
